### ISSUE TITLE
Battle portals do not unlock

### ISSUE THREAD

**Issue by Criticp** [Water-and-Critic/KH3-Rando-GoA#33]
The logic for Anti Aqua messes stuff up and causes the player to be sent to the GoA causing all battle protals to remain locked. Having them all unlock automatically should be done as well.

**Comment by WaterKH** [comment]
[g_ex_battleportal_01.zip](https://github.com/Water-and-Critic/KH3-Rando-GoA/files/8503326/g_ex_battleportal_01.zip)

This allows all battleportals to be active before reaching the end of the game.

Path: \Content\Blueprints\Gimmick\ex\g_ex_battleportal
