### ISSUE TITLE
Faster Crab Collection

### ISSUE THREAD

**Issue by Criticp** [Water-and-Critic/KH3-Rando-GoA#60]
Each crab will be worth three times the usual amount to allow for less time needed to collect crabs.

**Comment by WaterKH** [comment]
[g_ca_KaniDiveGim_PrizeData.zip](https://github.com/Water-and-Critic/KH3-Rando-GoA/files/8503240/g_ca_KaniDiveGim_PrizeData.zip)

This allows the first dive gimmick crate to hold 1700 crabs, instantly skipping the entire crab search.
Location: \Content\DataTable\Gimmick\Prize
